#!/bin/bash

set -eo pipefail
export SCRIPTNAME='BTOP_SPECIAL_WORKSPACE'

source "${HOME}/.config/hypr/scripts/common-functions.sh"
if [ "$(hyprland_is_running)" = 'false' ]; then
  debug 'Hyprland is not running, exiting'
  exit 1
fi
BTOP_WORKSPACE='btop_sw'

workspace=$(hyprctl --instance "${HYPRLAND_INSTANCE_SIGNATURE}" workspaces | grep ${BTOP_WORKSPACE} || true)
debug 'Got workspace (or not):' ${workspace}
if [[ -z ${workspace} ]]; then
  debug 'Executing btop'
  hyprctl --instance "${HYPRLAND_INSTANCE_SIGNATURE}" dispatch exec '[workspace special:btop_sw silent] kitty btop'
fi

hyprctl --instance "${HYPRLAND_INSTANCE_SIGNATURE}" dispatch togglespecialworkspace ${BTOP_WORKSPACE}

exit 0
