#!/bin/bash

set -eo pipefail
export SCRIPTNAME='EVENT_HANDLER'

source "${HOME}/.config/hypr/scripts/common-functions.sh"
if [ "$(hyprland_is_running)" = 'false' ]; then
  debug 'Hyprland is not running, exiting'
  exit 1
fi

mkfifo ${WAYBAR_SW_NAMED_PIPE}

function handle_event() {
  local -r __event=${1}
  case ${__event} in
    activespecial*)
      pkill -RTMIN+2 waybar
      echo ${__event} > ${WAYBAR_SW_NAMED_PIPE}
      ;;
    *)
      ;;
  esac
}

socat - "UNIX-CONNECT:/tmp/hypr/${HYPRLAND_INSTANCE_SIGNATURE}/.socket2.sock" \
  | while read -r line; do handle_event "${line}"; done

debug 'Event stream has ended, exiting'
rm -f ${WAYBAR_SW_NAMED_PIPE}
exit 0