#!/bin/bash

clear && tput civis

while :; do
  tput cup 0 0 && cat << LOREM_IPSUM | nms -a -s
Lorem ipsum dolor sit amet, consectetur adipiscing elit,
sed do eiusmod tempor incididunt ut labore et dolore magna
aliqua. At tellus at urna condimentum mattis pellentesque
id. Viverra vitae congue eu consequat ac felis. Amet
venenatis urna cursus eget nunc scelerisque viverra mauris.
Ac odio tempor orci dapibus. Fusce ut placerat orci nulla
pellentesque dignissim. Tellus orci ac auctor augue mauris.
Nibh cras pulvinar mattis nunc sed blandit libero.
Vestibulum lectus mauris ultrices eros. Tortor at auctor
urna nunc id cursus metus. Donec et odio pellentesque
diam volutpat commodo. Fames ac turpis egestas maecenas
pharetra convallis posuere. Nibh mauris cursus mattis
molestie a iaculis at.
LOREM_IPSUM
sleep 2
done

tput cnorm
exit 0
