#!/bin/bash

set -e

export SCRIPTNAME='HYPRLAND_STARTUP'
source "${HOME}/.config/hypr/scripts/common-functions.sh"
if [ hyprland_is_running = 'false' ]; then
  debug 'Hyprland is not running, exiting'
  exit 1
fi

# Getting rid of hyprpaper setter
if [ -f "${HYPRPAPER_SETTER_PIDFILE}" ]; then
  debug 'Killing hyprpaper-setter'
  kill -KILL $(cat ${HYPRPAPER_SETTER_PIDFILE}) 2>/dev/null || true
  rm -f "${HYPRPAPER_SETTER_PIDFILE}" 2>/dev/null || true
fi

debug 'Startup finished'
exit 0
