#!/bin/bash

set -eo pipefail
export SCRIPTNAME='LAYOUT_SWITCHER'

source "${HOME}/.config/hypr/scripts/common-functions.sh"
if [ "$(hyprland_is_running)" = 'false' ]; then
  debug 'Hyprland is not running, exiting'
  exit 1
fi

active_keyboard=$(hyprctl --instance "${HYPRLAND_INSTANCE}" devices -j \
  | jq -r '.keyboards | map(select(.main)) | .[0] | .name')
if [ -z ${active_keyboard} ]; then
  debug 'Keyboard not found, exiting'
  exit 2
fi
debug "Found active keyboard: ${active_keyboard}"

hyprctl --instance "${HYPRLAND_INSTANCE_SIGNATURE}" switchxkblayout ${active_keyboard} next && pkill -RTMIN+1 waybar

exit 0
