#!/bin/bash

if [[ -n "${TRIGGER_PY_HYPR_WRAPPER_DEBUG_MODE}" ]]; then
  set -xv
fi

__TERMINAL_OUTPUT=''
[[ -t 1 ]] && __TERMINAL_OUTPUT='1'
readonly __TERMINAL_OUTPUT
__RED=$([[ -n "${__TERMINAL_OUTPUT}" ]] && echo '\033[0;31m' || true)
__NO_COLOR=$([[ -n "${__TERMINAL_OUTPUT}" ]] && echo '\033[0m' || true)
readonly __RED __NO_COLOR

PY_HYPR_WRAPPER_RUNTIME_DIR="${XDG_RUNTIME_DIR}/py-hypr-wrapper"
PY_HYPR_WRAPPER_SOCKET="${PY_HYPR_WRAPPER_RUNTIME_DIR}/py-hypr-wrapper.socket"
WAYBAR_KEYBOARD_LAYOUT_OUTFILE="${PY_HYPR_WRAPPER_RUNTIME_DIR}/waybar-active-keyboard-layout"
WAYBAR_SPECIAL_WORKSPACE_DISPLAYNAME_OUTFILE="${PY_HYPR_WRAPPER_RUNTIME_DIR}/waybar-special-workspace-displayname"

function script_usage() {
  cat << USAGE 1>&2
Description:
  Trigger the py-hypr-wrapper module for DE like functionalities.

Usage:
  ${0} [FLAGS]

Flags:
  -1, --btop-special-workspace: Toggle a scratchpad/special workspace for btop
  -2, --switch-keyboard-layout: Switch active keyboard layout to the next one
  -3, --toggle-wallpaper-changing: Toggle the changing of the wallpapers (default: Enabled)
  -4, --keyboard-layout-switched: Should be called when the keyboard layout has been switched
  -5, --special-workspace-button-onclick: Toggle the special workspace 'status'
  -6, --special-workspace-displayname: Should be called when a special workspace is toggled
  -h, --help: Display help

Environment variables:
  TRIGGER_PY_HYPR_WRAPPER_DEBUG_MODE: enables debug mode (bash -xv)
USAGE
}

function die_with_usage() {
  local -r _error_message="${1}"
  local -r _exit_code="${2:-42}"
  echo -e "${__RED}${0}: ERROR -> ${_error_message}${__NO_COLOR}\n" 1>&2
  script_usage
  exit "${_exit_code}"
}

function send_call_to_py_hypr_wrapper() {
  echo "${1}" | socat - "UNIX-CONNECT:${PY_HYPR_WRAPPER_SOCKET}" 1>&2
}

function btop_special_workspace() {
  send_call_to_py_hypr_wrapper '_BSW'
}

function switch_keyboard_layout() {
  send_call_to_py_hypr_wrapper '_SKL'
}

function toggle_wallpaper_changing() {
  send_call_to_py_hypr_wrapper '_TWC'
}

function keyboard_layout_switched() {
  send_call_to_py_hypr_wrapper '_KLS'
  cat "${WAYBAR_KEYBOARD_LAYOUT_OUTFILE}"
}

function special_workspace_button_onclick() {
  send_call_to_py_hypr_wrapper '_SWBO'
}

function special_workspace_displayname() {
  send_call_to_py_hypr_wrapper '_SWD'
  cat "${WAYBAR_SPECIAL_WORKSPACE_DISPLAYNAME_OUTFILE}"
}

while [ ${#} -gt 0 ]; do
  case "${1}" in
    --btop-special-workspace|-1)
      btop_special_workspace
      ;;
    --switch-keyboard-layout|-2)
      switch_keyboard_layout
      ;;
    --toggle-wallpaper-changing|-3)
      toggle_wallpaper_changing
      ;;
    --keyboard-layout-switched|-4)
      keyboard_layout_switched
      ;;
    --special-workspace-button-onclick|-5)
      special_workspace_button_onclick
      ;;
    --special-workspace-displayname|-6)
      special_workspace_displayname
      ;;
    --help|-h)
      script_usage
      exit 0
      ;;
  esac
  shift
done
