#!/bin/bash

SCRIPTNAME='WAYBAR_SPECIAL_WORKSPACE_DISPLAYNAME'
source "${HOME}/.config/hypr/scripts/common-functions.sh"
if [ "$(hyprland_is_running)" = 'false' ]; then
  debug 'Hyprland is not running, exiting'
  exit 1
fi

debug 'Someone requested a run'
if hyprctl -j activewindow | jq '.workspace | .name' | tr -d '"' | grep special 1>&2; then
  echo '<span size="125%">󰰢</span>'
else
  echo '<span size="125%">󰰣</span>'
fi

exit 0
