#!/bin/bash

SCRIPTNAME='WAYBAR_SPECIAL_WORKSPACE_ONCLICK'
source "${HOME}/.config/hypr/scripts/common-functions.sh"
if [ "$(hyprland_is_running)" = 'false' ]; then
  debug 'Hyprland is not running, exiting'
  exit 1
fi

runner_id=${RANDOM}

debug "[${runner_id}]: Someone requested a run"
special_workspace_name=$(cat ${WAYBAR_SW_RUNFILE})
if [ -n "${special_workspace_name}" ]; then
  swname="$(echo ${special_workspace_name} | cut -d':' -f2)"
  hyprctl --instance "${HYPRLAND_INSTANCE_SIGNATURE}" dispatch togglespecialworkspace "${special_workspace_name}"
else
  debug "[${runner_id}]:" "No special workspace, opening STATUS"
  hyprctl --instance "${HYPRLAND_INSTANCE_SIGNATURE}" dispatch togglespecialworkspace 'status'
fi

debug "[${runner_id}]: Exiting"
exit 0