#!/bin/bash

SCRIPTNAME='WAYBAR_SPECIAL_WORKSPACE_ONCLICK'
source "${HOME}/.config/hypr/scripts/common-functions.sh"
if [ "$(hyprland_is_running)" = 'false' ]; then
  debug 'Hyprland is not running, exiting'
  exit 1
fi

debug 'Someone requested a run'
special_workspace_full_name=$(hyprctl --instance "${HYPRLAND_INSTANCE_SIGNATURE}" -j activewindow \
  | jq '.workspace | .name' | tr -d '"' | grep special)
if [ -n "${special_workspace_full_name}" ]; then
  debug "Found special workspace: ${special_workspace_full_name}"
  swname="$(echo ${special_workspace_full_name} | cut -d':' -f2)"
  hyprctl --instance "${HYPRLAND_INSTANCE_SIGNATURE}" dispatch togglespecialworkspace "${swname}"
else
  debug "No special workspace, opening STATUS"
  hyprctl --instance "${HYPRLAND_INSTANCE_SIGNATURE}" dispatch togglespecialworkspace 'status'
fi

pkill -RTMIN+2 waybar

exit 0